"""Padrões globais e regras declarativas de candidatos."""

from __future__ import annotations

from diskaudit.models import CandidateRule

PATTERNS: list[tuple[str, str]] = [
    ("WinSxS", r"\\WinSxS$"),
    ("Downloads", r"\\Downloads$"),
    ("AppData\\Local\\Packages", r"\\AppData\\Local\\Packages$"),
    ("$Recycle.Bin", r"\\?\$Recycle\.Bin$"),
    ("wsl", r"\\wsl$"),
    ("AppData\\Local\\Programs", r"\\AppData\\Local\\Programs$"),
    ("Docker", r"\\Docker$"),
    ("node_modules", r"\\node_modules$"),
    ("AppData\\Local\\Temp", r"\\AppData\\Local\\Temp$"),
    ("Temp", r"\\Temp$"),
    ("Steam", r"\\Steam$"),
    (".cache", r"\\\.cache$"),
    (".vscode", r"\\\.vscode$"),
    ("AppData\\Roaming\\Code", r"\\AppData\\Roaming\\Code$"),
    (".gradle", r"\\\.gradle$"),
    ("Epic Games", r"\\Epic Games$"),
    ("Installer", r"\\Installer$"),
    ("AppData\\Local\\npm-cache", r"\\AppData\\Local\\npm-cache$"),
    ("Logs", r"\\Logs$"),
    (
        "AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache",
        r"\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache$",
    ),
    (
        "AppData\\Local\\Mozilla\\Firefox\\Profiles\\…\\cache2",
        r"\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\[^\\]+\\cache2$",
    ),
    (
        "AppData\\Local\\Opera Software\\…\\Cache",
        r"\\AppData\\Local\\Opera Software\\[^\\]+\\Cache$",
    ),
    (
        "AppData\\Local\\Google\\Chrome\\User Data",
        r"\\AppData\\Local\\Google\\Chrome\\User Data$",
    ),
    ("AppData\\Local\\Discord", r"\\AppData\\Local\\Discord$"),
    (".m2", r"\\\.m2$"),
    ("OneDrive", r"\\OneDrive$"),
    (
        "AppData\\Local\\Microsoft\\Windows\\WebCache",
        r"\\AppData\\Local\\Microsoft\\Windows\\WebCache$",
    ),
]

CANDIDATE_RULES: list[CandidateRule] = [
    CandidateRule(r"\\?\$Recycle\.Bin$", "seguro", "Lixeira", "Esvaziar Lixeira", "recycle", 0.1),
    CandidateRule(r"\\AppData\\Local\\Temp$", "seguro", "Cache", "Esvaziar %temp%", "temp", 0.5),
    CandidateRule(
        r"\\AppData\\Local\\Opera Software\\[^\\]+\\Cache$",
        "seguro",
        "Cache de navegador",
        "Limpar cache do Opera",
        "browser_cache",
        0.3,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\[^\\]+\\cache2$",
        "seguro",
        "Cache de navegador",
        "Limpar cache do Firefox",
        "browser_cache",
        0.3,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache$",
        "seguro",
        "Cache de navegador",
        "Limpar cache do Chrome",
        "browser_cache",
        0.3,
    ),
    CandidateRule(
        r"\\AppData\\Local\\npm-cache$",
        "seguro",
        "Cache de pacotes",
        "npm cache clean --force",
        "npm_cache",
        0.5,
    ),
    CandidateRule(
        r"\\AppData\\Local\\pnpm$",
        "seguro",
        "Cache de pacotes",
        "pnpm store prune",
        "npm_cache",
        0.5,
    ),
    CandidateRule(
        r"\\AppData\\Local\\pip\\cache$",
        "seguro",
        "Cache de pacotes",
        "pip cache purge",
        "npm_cache",
        0.5,
    ),
    CandidateRule(
        r"\\Windows\\WinSxS$",
        "cuidado",
        "Windows",
        "DISM /Online /Cleanup-Image /StartComponentCleanup /ResetBase",
        "winsxs",
        5.0,
    ),
    CandidateRule(
        r"\\\.lmstudio\\models$",
        "cuidado",
        "Modelos LLM",
        "Manter apenas modelos em uso",
        "llm_models",
        5.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Claude-3p$",
        "cuidado",
        "App órfão",
        "Deletar após confirmar versão UWP do Claude",
        "orphan_claude",
        1.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Docker$",
        "cuidado",
        "Dev (Docker)",
        "docker system prune -a --volumes",
        "docker",
        2.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\wsl$",
        "cuidado",
        "Dev (WSL)",
        "wsl --unregister distros não usadas",
        "wsl",
        1.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Android$",
        "cuidado",
        "Dev (Android)",
        "SDK Manager → remover APIs não usadas",
        "android",
        2.0,
    ),
    CandidateRule(
        r"\\\.android\\avd$",
        "cuidado",
        "Dev (Android)",
        "Remover emuladores não usados",
        "avd",
        2.0,
    ),
    CandidateRule(
        r"\\AppData\\Roaming\\\.minecraft$",
        "cuidado",
        "Jogo",
        "Limpar mods/packs ou desinstalar",
        "minecraft",
        3.0,
    ),
    CandidateRule(r"\\AppData\\Local\\Roblox$", "cuidado", "Jogo", "Desinstalar se não joga", "generic", 2.0),
    CandidateRule(
        r"\\AppData\\Local\\CapCut$",
        "cuidado",
        "Edição de vídeo",
        "Limpar cache de mídia no CapCut",
        "generic",
        1.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Steam$",
        "cuidado",
        "Jogos",
        "Desinstalar jogos não usados",
        "generic",
        2.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\EpicGames$",
        "cuidado",
        "Jogos",
        "Desinstalar jogos Epic não usados",
        "generic",
        2.0,
    ),
    CandidateRule(
        r"\\AppData\\Local\\BlueStacks",
        "cuidado",
        "Emulador",
        "Desinstalar se não usa",
        "generic",
        0.5,
    ),
    CandidateRule(
        r"\\AppData\\Local\\Ollama$",
        "seguro",
        "Cache de updater",
        "Deletar updates_v2/",
        "updater",
        0.5,
    ),
    CandidateRule(r"\\Music$", "nao_tocar", "Pessoal (música)", "Backup em nuvem/HD externo", "personal", 3.0),
    CandidateRule(
        r"\\Videos$",
        "nao_tocar",
        "Pessoal (vídeo)",
        "Mover para nuvem se pouco acessado",
        "personal",
        3.0,
    ),
    CandidateRule(r"\\Pictures$", "nao_tocar", "Pessoal", "Revisar manualmente", "personal", 2.0),
    CandidateRule(
        r"\\Documents$",
        "nao_tocar",
        "Pessoal (documentos)",
        "Revisar manualmente",
        "personal",
        5.0,
    ),
    CandidateRule(r"\\pagefile\.sys$", "nao_tocar", "Sistema", "Não mexer (Windows gerencia)", "system", 0.1),
    CandidateRule(r"\\hiberfil\.sys$", "nao_tocar", "Sistema", "Não mexer", "system", 0.1),
]
